database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: <password>
  url: jdbc:postgresql://<db_url>/emailservice?currentSchema=application

logging:
  level: INFO
  loggers:
    email: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8090

mailgun:
  api: 'https://api.mailgun.net/v3/<domain>/messages'
  apiKey: '<key>'
  from: 'Name <name@name.tld>'